<?php

namespace LivraisonBundle\Repository;

/**
 * LivreureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivreureRepository extends \Doctrine\ORM\EntityRepository
{
}
