<?php

namespace GestionStockBundle\Repository;

use Doctrine\ORM\Query\Expr\Join;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
    public function findproduit(){

        $query=$this->getEntityManager()
            ->createQuery("select p from GestionStockBundle:Produit p
        where p.supprimer=0");
        return $query->getResult() ;

    }
    public function findproduitsupprimer(){

        $query=$this->getEntityManager()
            ->createQuery("select p from GestionStockBundle:Produit p
        where p.supprimer=1");
        return $query->getResult() ;

    }
    public function findProduitNonStocke(){
        $query=$this->getEntityManager()
            ->createQuery("select p.id, p.description, p.quantite
             from GestionStockBundle:Produit p
             where p.supprimer=0");
        return $query->getResult() ;


    }


}
