<?php

namespace GestionStockBundle\Repository;

/**
 * StockageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockageRepository extends \Doctrine\ORM\EntityRepository
{

}
