<?php

namespace GestionVenteBundle\Repository;

/**
 * CommandeVenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeVenteRepository extends \Doctrine\ORM\EntityRepository
{
}
