<?php

namespace GestionVenteBundle\Repository;

/**
 * CommandeClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeClientRepository extends \Doctrine\ORM\EntityRepository
{
}
