<?php

namespace GestionAchatBundle\Repository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCommands($idFournisseur){
        $query = $this->getEntityManager()
            ->createQuery("SELECT c FROM GestionAchatBundle:Commande c WHERE c.fournisseur = :idFournisseur AND c.etat = 'en attente'")->setParameter('idFournisseur', $idFournisseur);
        return $query->getResult();
    }

}
