<?php

namespace GestionAchatBundle\Repository;

/**
 * fournisseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FournisseurRepository extends \Doctrine\ORM\EntityRepository
{
    public function findFournisseurByIdUser($idUser){
        $query = $this->getEntityManager()
            ->createQuery("SELECT f FROM GestionAchatBundle:Fournisseur f WHERE f.user = :idUser")->setParameter('idUser', $idUser);
        return $query->getResult();
    }
}
