<?php

namespace GestionAchatBundle\Repository;

/**
 * fournisseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class fournisseurRepository extends \Doctrine\ORM\EntityRepository
{
}
