<?php

namespace GestionAchatBundle\Repository;

/**
 * OmarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OmarRepository extends \Doctrine\ORM\EntityRepository
{
}
